import fs from 'node:fs';
import zlib from 'node:zlib';
import crypto from 'node:crypto';
import path from 'node:path';

const PNG = Buffer.from([137,80,78,71,13,10,26,10]);
const crc32 = data => { let c=0xffffffff; for (const b of data) { c^=b; for(let i=0;i<8;i++) c=(c>>>1)^((c&1)?0xedb88320:0); } return (c^0xffffffff)>>>0; };
const chunk=(type,data)=>{const t=Buffer.from(type),o=Buffer.alloc(12+data.length);o.writeUInt32BE(data.length);t.copy(o,4);data.copy(o,8);o.writeUInt32BE(crc32(Buffer.concat([t,data])),8+data.length);return o;};
export function readPng(file){const b=fs.readFileSync(file);if(!b.subarray(0,8).equals(PNG))throw Error('invalid PNG signature');let p=8,w,h,depth,colour,parts=[];while(p<b.length){const n=b.readUInt32BE(p),t=b.toString('ascii',p+4,p+8),d=b.subarray(p+8,p+8+n);p+=n+12;if(t==='IHDR'){w=d.readUInt32BE();h=d.readUInt32BE(4);depth=d[8];colour=d[9];}if(t==='IDAT')parts.push(d);if(t==='IEND')break;}if(depth!==8||(colour!==6&&colour!==2))throw Error('only 8-bit RGB/RGBA PNG supported');const bpp=colour===6?4:3,raw=zlib.inflateSync(Buffer.concat(parts)),srcStride=w*bpp,rawRow=Buffer.alloc(srcStride),prevRow=Buffer.alloc(srcStride),outStride=w*4,out=Buffer.alloc(h*outStride);let q=0;for(let y=0;y<h;y++){const f=raw[q++],row=raw.subarray(q,q+srcStride);q+=srcStride;for(let x=0;x<srcStride;x++){const a=x>=bpp?rawRow[x-bpp]:0,u=prevRow[x],ul=x>=bpp?prevRow[x-bpp]:0;let v=row[x];if(f===1)v+=a;else if(f===2)v+=u;else if(f===3)v+=Math.floor((a+u)/2);else if(f===4){const z=a+u-ul,pa=Math.abs(z-a),pb=Math.abs(z-u),pc=Math.abs(z-ul);v+=pa<=pb&&pa<=pc?a:pb<=pc?u:ul;}else if(f!==0)throw Error('unsupported PNG filter');rawRow[x]=v&255;}if(colour===6){rawRow.copy(out,y*outStride);}else{for(let x=0;x<w;x++){const si=x*3,di=y*outStride+x*4;out[di]=rawRow[si];out[di+1]=rawRow[si+1];out[di+2]=rawRow[si+2];out[di+3]=255;}}rawRow.copy(prevRow);}return {width:w,height:h,data:out};}
export function writePng(file,w,h,data){const raw=Buffer.alloc(h*(w*4+1));for(let y=0;y<h;y++){raw[y*(w*4+1)]=0;data.copy(raw,y*(w*4+1)+1,y*w*4,(y+1)*w*4);}const ih=Buffer.alloc(13);ih.writeUInt32BE(w);ih.writeUInt32BE(h,4);ih[8]=8;ih[9]=6;fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,Buffer.concat([PNG,chunk('IHDR',ih),chunk('IDAT',zlib.deflateSync(raw)),chunk('IEND',Buffer.alloc(0))]));}
export const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
export function comparePixels(a,b){if(a.width!==b.width||a.height!==b.height)return {dimension_mismatch:true,width:a.width,height:a.height};let diff=0,mae=0,max=0,out=Buffer.alloc(a.data.length);for(let i=0;i<a.data.length;i+=4){let changed=false;for(let c=0;c<4;c++){const e=Math.abs(a.data[i+c]-b.data[i+c]);mae+=e;max=Math.max(max,e);changed ||= e>0;out[i+c]=e?255:0;}if(changed)diff++;out[i+3]=255;}return {width:a.width,height:a.height,total_pixels:a.width*a.height,different_pixels:diff,different_ratio:diff/(a.width*a.height),mean_absolute_error:mae/(a.width*a.height*4),max_channel_error:max,diffData:out};}
